[package]
name = "quick-modbus"
version = "1.0.1"
authors = ["Mario Baldini <mario.baldini@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmodbus-rs = "0.8.3"
failure = "*"